create or replace table finance_db.public.fact_pbt_finance_metrics
cluster by (last_updated_at)
(
    record_id varchar(64) primary key not null,
    row_hash varchar(64),
    acv float,
    acv_prior float,
    amount_usd float,
    anchor_date_calc date,
    billing_category varchar,
    billing_period varchar,
    closedate date,
    core_ent_flag varchar,
    currency varchar,
    data_valid_thru date,
    date date,
    direct_ecomm_flag varchar,
    direct_indirect varchar,
    -- elt_metrics_id varchar NOT NULL,
    globalultimateparentupperclean varchar,
    in_current_year_flag boolean,
    in_month_flag boolean,
    in_prev_quarter_flag boolean,
    in_quarter_flag boolean,
    invoice_no varchar,
    is_deleted boolean,
    last_updated_at timestamp_ntz,
    license_renewal varchar,
    my float,
    multiyear_flag int,
    new_expansion varchar,
    order_type_final varchar,
    pbt_group varchar,
    pf_hold_amount float,
    pf_hold_flag int,
    product varchar,
    product_for_reporting varchar,
    product_hub varchar,
    product_name varchar,
    product_parent varchar,
    region varchar,
    report_month date,
    saletype varchar,
    snapshot_date datetime,
    snapshot_date_offset int,
    source varchar,
    source_group varchar,
    status_inq_pull varchar,
    type varchar
)
; 
insert into finance_db.public.fact_pbt_finance_metrics
(
    record_id,
    row_hash,
    acv,
    acv_prior,
    amount_usd,
    anchor_date_calc,
    billing_category,
    billing_period,
    closedate,
    core_ent_flag,
    currency,
    data_valid_thru,
    date,
    direct_ecomm_flag,
    direct_indirect,
    -- elt_metrics_id,
    globalultimateparentupperclean,
    in_current_year_flag,
    in_month_flag,
    in_prev_quarter_flag,
    in_quarter_flag,
    invoice_no,
    is_deleted,
    last_updated_at,
    license_renewal,
    my,
    multiyear_flag,
    new_expansion,
    order_type_final,
    pbt_group,
    pf_hold_amount,
    pf_hold_flag,
    product,
    product_for_reporting,
    product_hub,
    product_name,
    product_parent,
    region,
    report_month,
    saletype,
    snapshot_date,
    snapshot_date_offset,
    source,
    source_group,
    status_inq_pull,
    type
)
select 
    record_id,
    row_hash,
    acv,
    acv_prior,
    amount_usd,
    anchor_date_calc,
    billing_category,
    billing_period,
    closedate,
    core_ent_flag,
    currency,
    data_valid_thru,
    date,
    direct_ecomm_flag,
    direct_indirect,
    -- elt_metrics_id,
    globalultimateparentupperclean,
    in_current_year_flag,
    in_month_flag,
    in_prev_quarter_flag,
    in_quarter_flag,
    invoice_no,
    TRUE is_deleted,
    current_timestamp() last_updated_at,
    license_renewal,
    my,
    multiyear_flag,
    new_expansion,
    order_type_final,
    pbt_group,
    pf_hold_amount,
    pf_hold_flag,
    product,
    product_for_reporting,
    product_hub,
    product_name,
    product_parent,
    region,
    report_month,
    saletype,
    snapshot_date,
    snapshot_date_offset,
    source,
    source_group,
    status_inq_pull,
    type
from 
    finance_db.public.vw_elt_metrics